//
//
//

let cards: [Card] = [
    Card(id: .back, number: .back, suit: .back),
    
    Card(id: .spade1, number: .num1, suit: .spade),
    Card(id: .spade2, number: .num2, suit: .spade),
    Card(id: .spade3, number: .num3, suit: .spade),
    Card(id: .spade4, number: .num4, suit: .spade),
    Card(id: .spade5, number: .num5, suit: .spade),
    Card(id: .spade6, number: .num6, suit: .spade),
    Card(id: .spade7, number: .num7, suit: .spade),
    Card(id: .spade8, number: .num8, suit: .spade),
    Card(id: .spade9, number: .num9, suit: .spade),
    Card(id: .spade10, number: .num10, suit: .spade),
    Card(id: .spade11, number: .num11, suit: .spade),
    Card(id: .spade12, number: .num12, suit: .spade),
    Card(id: .spade13, number: .num13, suit: .spade),

    Card(id: .heart1, number: .num1, suit: .heart),
    Card(id: .heart2, number: .num2, suit: .heart),
    Card(id: .heart3, number: .num3, suit: .heart),
    Card(id: .heart4, number: .num4, suit: .heart),
    Card(id: .heart5, number: .num5, suit: .heart),
    Card(id: .heart6, number: .num6, suit: .heart),
    Card(id: .heart7, number: .num7, suit: .heart),
    Card(id: .heart8, number: .num8, suit: .heart),
    Card(id: .heart9, number: .num9, suit: .heart),
    Card(id: .heart10, number: .num10, suit: .heart),
    Card(id: .heart11, number: .num11, suit: .heart),
    Card(id: .heart12, number: .num12, suit: .heart),
    Card(id: .heart13, number: .num13, suit: .heart),

    Card(id: .diamond1, number: .num1, suit: .diamond),
    Card(id: .diamond2, number: .num2, suit: .diamond),
    Card(id: .diamond3, number: .num3, suit: .diamond),
    Card(id: .diamond4, number: .num4, suit: .diamond),
    Card(id: .diamond5, number: .num5, suit: .diamond),
    Card(id: .diamond6, number: .num6, suit: .diamond),
    Card(id: .diamond7, number: .num7, suit: .diamond),
    Card(id: .diamond8, number: .num8, suit: .diamond),
    Card(id: .diamond9, number: .num9, suit: .diamond),
    Card(id: .diamond10, number: .num10, suit: .diamond),
    Card(id: .diamond11, number: .num11, suit: .diamond),
    Card(id: .diamond12, number: .num12, suit: .diamond),
    Card(id: .diamond13, number: .num13, suit: .diamond),

    Card(id: .club1, number: .num1, suit: .club),
    Card(id: .club2, number: .num2, suit: .club),
    Card(id: .club3, number: .num3, suit: .club),
    Card(id: .club4, number: .num4, suit: .club),
    Card(id: .club5, number: .num5, suit: .club),
    Card(id: .club6, number: .num6, suit: .club),
    Card(id: .club7, number: .num7, suit: .club),
    Card(id: .club8, number: .num8, suit: .club),
    Card(id: .club9, number: .num9, suit: .club),
    Card(id: .club10, number: .num10, suit: .club),
    Card(id: .club11, number: .num11, suit: .club),
    Card(id: .club12, number: .num12, suit: .club),
    Card(id: .club13, number: .num13, suit: .club),

    Card(id: .blackJocker, number: .joker, suit: .joker),
    Card(id: .whiteJocker, number: .joker, suit: .joker),
]
